In [41]:
import pandas as pd
import numpy as np

pd.options.mode.chained_assignment = None
# pd.set_option('display.max_rows', None)
# pd.set_option('display.max_colwidth', None)

1. Shot chart + table
2. Head to head comparison
3. Scoring comparison to averages (x2)
4. Offensive comparison to averages (x2)
5. Miscellaneous comparison to averages (x2)
6. Advanced comparison to averages (x2)
7. Lineup advanced

## Head-to-Head

In [31]:
season = pd.read_csv("season_overview.csv").iloc[:, 1:]

head_to_head = season[(season.Date == 'November 6, 2021')]

head_to_head = head_to_head.iloc[0:2, :]
head_to_head.loc[len(head_to_head)] = list(head_to_head.columns)

head_to_head.to_csv("head_to_head.csv")
head_to_head

,Team,Field Goal,Field Goal %,3 Point,3 Point %,Free Throw,Free Throw %,Rebounds,Assists,Turnovers,...,FGM,FGA,3PM,3PA,FTM,FTA,FG%,3P%,FT%,Chicago
0,Chicago,24-53,45.3%,11-32,34.4%,19-27,70.4%,36,17,17,...,24,53,11,32,19,27,45.283019,34.375,70.37037,True
1,Colorado College,25-57,43.9%,6-22,27.3%,18-26,69.2%,32,10,12,...,25,57,6,22,18,26,43.859649,27.272727,69.230769,False
2,Team,Field Goal,Field Goal %,3 Point,3 Point %,Free Throw,Free Throw %,Rebounds,Assists,Turnovers,...,FGM,FGA,3PM,3PA,FTM,FTA,FG%,3P%,FT%,Chicago

## Scoring/Offensive/Miscellaneous Comparison

In [58]:
season_averages = pd.read_csv("season_averages.csv")

traditional_comparisons = pd.concat([season_averages, head_to_head])

traditional_comparisons.to_csv("traditional_comparisons.csv")
traditional_comparisons

,Chicago,Chicago.1,Unnamed: 0,Rebounds,Assists,Turnovers,Points off Turnovers,2nd Chance Points,Points in the Paint,Fastbreak Points,...,Team,Field Goal,Field Goal %,3 Point,3 Point %,Free Throw,Free Throw %,Time of Largest Lead,Opponent,Date
0,UChicago,UChicago,0.5,35.8,12.1,12.9,11.0,8.7,24.1,2.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Opponent,Opponent,0.5,35.6,12.0,10.8,14.3,7.2,33.0,7.4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,Chicago,Unnamed: 0,Rebounds,Assists,Turnovers,Points off Turnovers,2nd Chance Points,Points in the Paint,Fastbreak Points,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,True,NaN,NaN,36,17,17,14,9,24.0,4.0,...,Chicago,24-53,45.3%,11-32,34.4%,19-27,70.4%,1st-05:29,Colorado College,"November 6, 2021"
1,False,NaN,NaN,32,10,12,16,1,32.0,14.0,...,Colorado College,25-57,43.9%,6-22,27.3%,18-26,69.2%,1st-18:48,Colorado College,"November 6, 2021"
2,Chicago,NaN,NaN,Rebounds,Assists,Turnovers,Points off Turnovers,2nd Chance Points,Points in the Paint,Fastbreak Points,...,Team,Field Goal,Field Goal %,3 Point,3 Point %,Free Throw,Free Throw %,Time of Largest Lead,Opponent,Date

## Advanced Comparison

## Lineup Advanced